apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ace-bpf
  name: ace-bpf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ace-bpf
  strategy: {}
  template:
    metadata:
      labels:
        app: ace-bpf
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         matchExpressions:
      #         - key: node-role.kubernetes.io/master
      #           operator: Exists
      #           values: ["master"]
      containers:
      - image: alexeldeib/bpfalpine
        command: ["sleep", "infinity"]
        name: bpfalpine
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /proc
          name: proc
        - mountPath: /sys
          name: sys
        - mountPath: /mnt/hostMount
          name: host
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: host
        hostPath:
          path: /
      