apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssh
  name: ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh
  strategy: {}
  template:
    metadata:
      labels:
        app: ssh
    spec:
      hostPID: true
      containers:
      - image: alexeldeib/godisk:latest
        command: ["bash", "start.sh"]
        name: ubuntu
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /opt
          name: opt
        # - mountPath: /dev
        #   name: dev
        #   mountPropagation: Bidirectional
        # - mountPath: /mnt
        #   name: mnt
        #   mountPropagation: Bidirectional
        # - mountPath: /mnt/fast
        #   name: fast
      volumes:
      - name: opt
        hostPath:
          path: /opt
      # - name: dev
      #   hostPath:
      #     path: /dev
      # - name: mnt
      #   hostPath:
      #     path: /mnt
      # - name: fast
      #   persistentVolumeClaim:
      #     claimName: example-local-claim
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: example-local-claim
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: fast-disks
